language: node_js
node_js:
- 6
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_bba0dbd5ff95_key -iv $encrypted_bba0dbd5ff95_iv
  -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name 'xcatliu'
- git config --global user.email 'xcatliu@gmail.com'
install:
- rvm install 2.3.1
- gem install sass
- gem install scss_lint
- npm install
script:
- bash ./.travis/deploy.sh
