language: node_js
node_js:
- 6
branches:
  only:
  - master
before_install:
- git config --global user.name 'xcatliu'
- git config --global user.email 'xcatliu@gmail.com'
install:
- npm install
script:
- bash ./.travis/deploy.sh
